### ISSUE TITLE
Episode 01: Intro to LC - Where to go for help

### ISSUE THREAD

**Issue by kekoziar** [LibraryCarpentry/lc-data-intro-archives#10]
This section has various grammar issues sprinkled throughout.  I also wonder if an ice breaker exercise would be useful here to help people identify people at their table (first point in this section)

**Comment by doingarchives** [comment]
This appears to combine two thoughts: grammatical corrections (a review is something we can look at in future pull requests) and a pedagogical intention to facilitate group dynamics - given that we want both virtual and physical lesson plans - maybe a simple pool as part of the set up for the course will help situate learners in the  museums \ archives \ records management intellectual domains.
