### ISSUE TITLE
Episode 01: Intro to LC - Objectives

### ISSUE THREAD

**Issue by kekoziar** [LibraryCarpentry/lc-data-intro-archives#11]
Learning Outcomes or Objectives should be measurable. Since it's difficult to measure someone's knowledge (eg 'to know') or understanding, the objectives should described using key words that allow measurement.  I personally use Bloom's Taxonomy.

I suggest 
_Know where to go for help during Library Carpentry_
is changed to
_Identify where to go for help during Library Carpentry Workshops_

**Comment by doingarchives** [comment]
There is considerable overlap and merging of concepts in archival repositories and 'museums'. Libraries - for these lessons and for the collection statistics is mostly about print resources.

ISO 18461:2016(en)
International museum statistics

has some useful information. I do think we want to articulate the existence and manipulation of data sets in these forums.

See EGMS

"A first provisional table - "ALOKMI (Abridged List of Key Museum Indicators)" - has been created. As a first step to comparison, it puts together a large number of relevant data from the various countries in a single table."
