### ISSUE TITLE
Episode 2: Task 2

### ISSUE THREAD

**Issue by kekoziar** [LibraryCarpentry/lc-data-intro-archives#12]
Since the learners are supposed to be archivists and sometimes librarians, I think it would be okay to use the term _provenance_ in the discussion bullet point:
_Discuss the provenance of the data. How many people ..._

**Comment by doingarchives** [comment]
@kekoziar True. The synergy between professional identities and data and the terminology is crucial to the lesson.

**Comment by doingarchives** [comment]
ISO 5127:2017(en)
Information and documentation — Foundation and vocabulary

3.6.2.1.09
provenance
relationships (3.1.1.12) between documents (3.1.1.38) and the organizations (3.1.1.55) or individuals that created, accumulated (3.2.1.37) and/or maintained and used them in the conduct of personal or corporate activity

[SOURCE: ISAAR (CPF):2003, 3 Glossary of terms and definitions, modified]

Note 1 to entry: See also “custody” (3.1.1.58); ISO 19115-1:2014, definition 4.16; ISO 19153:2014, definition 4.39; ISO/IEC 23000-15:2016, definition 3.4.1.
