### ISSUE TITLE
Episode 4: Regular expressions

### ISSUE THREAD

**Issue by jellenf** [LibraryCarpentry/lc-data-intro-archives#17]
We could re-work this with more library-specific examples. Got a good example related to using regex within the MarcEdit application from one of our catalogers that I will draft into something.

**Comment by doingarchives** [comment]
@jellenf The idea that Archives and collections (books, music, film, artifacts) management are the highest level ideas has been established. We'll be using ISO 5127 to specify the things archivists and collection managers do.
