### ISSUE TITLE
Episode 3: Foundations

### ISSUE THREAD

**Issue by sarasrking** [LibraryCarpentry/lc-data-intro-archives#19]
There are two pieces missing here - the last sentence of the paragraph is dangling, and there's no content under the 'Data structures for computers' paragraph:

Beyond the Interface
Much of the work that you do with data may be completed through a software interface. Your archival catalog and excel spreadsheets are interfaces that allow you to view your data more easily. The data itself is organized into structures that many of you will be familiar with but is much more text heavy and may not be as simple for humans to read. _The structures are simple for_

Data structures for computers

**Comment by drjwbaker** [comment]
Thanks @sarasrking. I've made a PR at https://github.com/LibraryCarpentry/lc-data-intro-archives/pull/20 to tidy this up. I note this lesson is now out of step with the [LC standard version](https://librarycarpentry.org/lc-data-intro/03-foundations/index.html) (e.g. we removed the 'Computer is Stupid' Language upon [suggestion by a user](https://github.com/LibraryCarpentry/lc-data-intro/issues/87)). Handing over to maintainers @kekoziar @jellenf @scottcpeterson to take a proper look when they have some time :)
