### ISSUE TITLE
lesson handout link in the guide does not resolve

### ISSUE THREAD

**Issue by marisastrong** [LibraryCarpentry/lc-data-intro-archives#5]
on the page
https://librarycarpentry.org/lc-data-intro-archives/guide/
the section at the top has a link that doesn't resolve - see below.

Making a handout
Librarians like handouts. To make a handout for this lesson, adapt/print from http://data-lessons.github.io/data-intro-archives/reference/.

**Comment by libcce** [comment]
Hi @marisastrong 😄 Thanks for this! I've made the change https://github.com/LibraryCarpentry/lc-data-intro-archives/commit/96cd4a09f7ef1b26f02b937b6f36fc2a66d0a6f5 and thanks for the reminder that we need to see if any Maintainers will take on this lesson. It currently doesn't have Maintainers (the current ones listed have moved on) and it has been in search of new Maintainers. If we don't get any then we will have to deprecate the lesson unfortunately. I've probably been holding on too long but I guess I believe that there is someone out there that wants to help 😄
